before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows

    ldflags:
      - -s -w -X github.com/cpendery/clac/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

winget:
  - name: clac
    publisher: cpendery
    short_description: IDE style command line auto complete
    license: "apache 2.0"
    publisher_url: https://github.com/cpendery
    publisher_support_url: "https://github.com/cpendery/clac/issues/new"
    package_identifier: cpendery.clac
    goamd64: v1
    commit_author:
      name: cpendery
      email: cpendery@vt.edu
    commit_msg_template: "{{ .PackageIdentifier }}: {{ .Tag }}"
    path: manifests/g/goreleaser/1.19
    homepage: "https://github.com/cpendery/clac"
    skip_upload: true
    release_notes: "{{.Changelog}}"
    tags:
      - golang
      - cli
    repository:
      owner: cpendery
      name: clac
      branch: main
chocolateys:
  - name: clac
    owners: cpendery
    title: Clac
    authors: cpendery
    project_url: https://github.com/cpendery/clac
    require_license_acceptance: false
    project_source_url: https://github.com/cpendery/clac
    bug_tracker_url: https://github.com/cpendery/clac/issues
    summary: IDE style command line auto complete
    description: IDE style command line auto complete
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1
